### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by melkir** [nazar-pc/spotify-to-vk#1]
I have paste 
https://oauth.vk.com/authorize?client_id=MyAppId&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=audio

And I have 
{"error":"invalid_request","error_description":"Security Error"}

Do you any idea why ?

**Comment by nazar-pc** [comment]
Unfortunately no, did you create standalone application?

**Comment by melkir** [comment]
After tried again it's ok I have my token, my spotify playlist contain over 900 musics. I can export them with Spotify Playlist Extractor, or get the link for my playlist but how can I get the link for each musics of my playlist ? Do I need to right click, copy the link for each song and paste them to spotify.txt ?

**Comment by nazar-pc** [comment]
Yes, exactly, select needed songs, right click, copy their links and put everything into spotify.txt

**Comment by melkir** [comment]
Ok, you are the man thx very much for this script :) !
Just saying, before using this script I had needed to install php (obsious) and enable the openssl extension for https.

**Comment by nazar-pc** [comment]
Good to know that it works for you)
Accuracy is far from perfect, don't hesitate to report another issue or send pull request if you'll find some ways to improve it.
