### ISSUE TITLE
Suggestion : Use Spotify api instead to get music name

### ISSUE THREAD

**Issue by melkir** [nazar-pc/spotify-to-vk#2]
Hi,
It's seems that sometimes, title or artist are not correct by using play.spotify.
Maybe it will be more efficient if we use the spotify api which return a json content with all informations needed.

**Comment by nazar-pc** [comment]
API would be definitely much more accurate, but it will make things much more complicated. I wanted just to get job done, and it works in most cases.
Pull request is appreciated though.

**Comment by joelgarciajr84** [comment]
I will code this

**Comment by melkir** [comment]
Nice !

**Comment by nazar-pc** [comment]
This was indeed implemented in #6, we already use API:)
