### ISSUE TITLE
Captcha needed

### ISSUE THREAD

**Issue by damirock** [nazar-pc/spotify-to-vk#3]
Hi Nazar,

Great work you've done!
I've tried to use your script, but all I've got are strings like 

> Macklemore & Ryan Lewis - Thrift Shop - feat. Wanz: Captcha needed

Is there any way to evade captcha?

**Comment by nazar-pc** [comment]
Only open manually in browser and type it. Script is not smart enough to do that)

**Comment by damirock** [comment]
But how exactly do you do that? I see the error in the console, got to the Spotify track URL, and then what?)

**Comment by nazar-pc** [comment]
Read vk.com API how to make audio search requests. Compose URL and open it in browser.

In response you'll get error and link to captcha image. Just open it, and send next search request with additional argument where you put text from captcha. After this you'll be able to make some number of requests without need for captcha)

By the way, it is possible to improve code, print link right in terminal and read captcha code from standard input, but I do not have time for that currently, feel free to send pull request for such feature, would be useful for others:)
