### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by dec0yable** [nazar-pc/spotify-to-vk#4]
how do i execute that php?

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/spotify-to-vk#run-the-process

**Comment by dec0yable** [comment]
yeah i have seen that but how do i run the php script? if u-i run it in an online php executer it says undefined offset in lines 128 129 130 and 135

**Comment by nazar-pc** [comment]
I have no idea what executer you have (it shouldn't do anything by just running code).
Read readme from the beginning to the end, please.

**Comment by dec0yable** [comment]
I have read it fully but i don't know how to do this step
Run the process
Execute in terminal `php spotify-to-vk.php`
 when i do this in terminal it says php isn't recognised as a command

**Comment by nazar-pc** [comment]
OS? PHP installed?
If you are on Windows you might need to specify full path, like:

```
C:\php\php.exe spotify-to-vk.php
```

On *nix sometimes you might need to run as:

```
php-cli spotify-to-vk.php
```

Or also specify full path.

**Comment by dec0yable** [comment]
windows and oh you need to install a program? do you need a web server too?

**Comment by dec0yable** [comment]
haven't used php before so...

**Comment by nazar-pc** [comment]
You, you need just PHP, not web server.
Also you have to switch to directory where your `spotify.txt` is placed

```
cd C:\spotify_downloads
C:\php\php.exe spotify-to-vk.php
```

Code is written in PHP, so you'll need it to run the code.

**Comment by dec0yable** [comment]
could not open input file... i switched to where spotify.txt is placed...

**Comment by dec0yable** [comment]
also thanks for helping me!

**Comment by nazar-pc** [comment]
> could not open input file...

What do you mean here? Which file?

**Comment by dec0yable** [comment]
the php file

**Comment by nazar-pc** [comment]
Is `spotify-to-vk.php` in the same directory with `spotify.txt`  where you switched to?

**Comment by dec0yable** [comment]
yes

**Comment by nazar-pc** [comment]
Then this is super weird.
Is there php-cli.exe or similar file?
Can you copy exact output from console?

**Comment by dec0yable** [comment]
command line also started as administrator

**Comment by dec0yable** [comment]
there is a php-cgi.exe and
could not open input file: spotify-to-vk.php

**Comment by dec0yable** [comment]
but no php-cli.exe

**Comment by nazar-pc** [comment]
It is too much honor to execute this code as administrator.
Copy, please, everything from console, including command you wrote, just everything that you see in it.
