### ISSUE TITLE
weird thing

### ISSUE THREAD

**Issue by beltrans** [nazar-pc/spotify-to-vk#5]
Hi, I'm actually having some issues with this script.

Once I run it, I get some errors of undefined offset on lines 128, 129, 130 and 135. Despite that fact, each time I keep downloading a unique song, which is not in the list. Can you help me?

![image](https://cloud.githubusercontent.com/assets/13665497/9096343/dd4f34ba-3bbc-11e5-994c-bf48f5a75017.png)

**Comment by nazar-pc** [comment]
It seems that Spotify changed page script is scanning, thus scanning fails.
Feel free to fix that and send pull request.

**Comment by beltrans** [comment]
I would, but I have no idea of programming haha. Thanks anyway
